<?php
namespace App\DB;

class SelectQueryBuilder extends QueryBuilder
{

    use Where;

    /**
     * @param $fields
     */

    function getColumns(){
        $str = '';
        foreach ($this->fields as $value){
            $str .= ' ' . $value['column'].',';
        }

        return trim($str, ',');
    }

    /**
     * @return string
     */

    function setQuery(){
        $this->query .= "SELECT {$this->getColumns($this->fields)} FROM public.{$this->table} ";
        return $this;
    }

    function getQuery()
    {
        return parent::getQuery().' '.$this->where; // TODO: Change the autogenerated stub
    }


}